"""users

Revision ID: 71cd1b91aedd
Revises: 7e9bab9a2076
Create Date: 2025-01-03 10:01:06.203736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cd1b91aedd'
down_revision: Union[str, None] = '7e9bab9a2076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'food_logs', 'users', ['user_id'], ['id'])
    op.add_column('safe_foods', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'safe_foods', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'safe_foods', type_='foreignkey')
    op.drop_column('safe_foods', 'user_id')
    op.drop_constraint(None, 'food_logs', type_='foreignkey')
    op.drop_column('food_logs', 'user_id')
    # ### end Alembic commands ###
