"""initial migration

Revision ID: 7e9bab9a2076
Revises: 
Create Date: 2025-01-03 09:36:00.007738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9bab9a2076'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=100), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_logs_id'), 'food_logs', ['id'], unique=False)
    op.create_table('safe_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food')
    )
    op.create_index(op.f('ix_safe_foods_id'), 'safe_foods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safe_foods_id'), table_name='safe_foods')
    op.drop_table('safe_foods')
    op.drop_index(op.f('ix_food_logs_id'), table_name='food_logs')
    op.drop_table('food_logs')
    # ### end Alembic commands ###
